Make deployment :poop: its self if Prince install fails.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+set -e # fail build if any part of install fails
 PRINCE_VERSION="10r5"
 echo "-----> Installing PrinceXML $PRINCE_VERSION"
 [ -d .downloads ] || mkdir .downloads
